# Generated by Django 3.2.5 on 2023-06-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_teacher'),
        ('teachers', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
