# Generated by Django 3.2.5 on 2023-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='media\\courses\x823\x06\x019\\default.png', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
